<?php

namespace Tests\Feature;

use App\Models\TodoList;
use Database\Factories\TodoListFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TodoListTest extends TestCase
{
    use RefreshDatabase;

    public $list;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->list = TodoList::factory()->create(['name' => 'my list']);

    }

    public function test_show_all_the_todos()
    {
        $this->withoutDeprecationHandling();

        $response = $this->getJson(route('todo-list.index'));

        $this->assertEquals(1, $this->count($response->json()));
    }

    public function test_show_single_todo()
    {
        $response = $this->getJson(route('todo-list.show', $this->list->id))
            ->assertOk()
            ->json();
        $this->assertEquals($response['name'], $this->list->name);
    }

    public function test_create_a_new_todo_list()
    {
        $list = TodoList::factory()->make();
        $respnonse = $this->postJson(route('todo-list.store'), ['name' => $list->name])
            ->assertCreated()
            ->json();

        $this->assertEquals($list->name, $respnonse['name']);
        $this->assertDatabaseHas('todo_lists', ['name' => $list->name]);

    }

    public function test_while_storing_todo_list_name_field_required()
    {
        $response = $this->postJson(route('todo-list.store'))
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['name']);
    }

    public function test_destroy_todo_list()
    {
        $this->deleteJson(route('todo-list.destroy', $this->list->id))
            ->assertNoContent();

        $this->assertDatabaseMissing('todo_lists', ['name' => $this->list->name]);
    }

    public function test_update_todo_list()
    {
        $this->patchJson(route('todo-list.update', $this->list->id), ['name' => 'updated name'])
            ->assertOk();

        $this->assertDatabaseHas('todo_lists', ['id' => $this->list->id, 'name' => 'updated name']);
    }

    public function test_while_updating_todo_list_name_required()
    {
        $this->withExceptionHandling();

        $this->patchJson(route('todo-list.update', $this->list->id), ['name' => ''])
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['name']);
    }
}
